In [1]:
import numpy as np  


In [4]:
state = {
    0: "Burger",
    1 : "Pizza",
    2 : "Hotdog"
}
print(state)
A = np.array([[0.2,0.6,0.2],[0.3,0.0,0.7],[0.5,0.0,0.5]])
print(A)

{0: 'Burger', 1: 'Pizza', 2: 'Hotdog'}
[[0.2 0.6 0.2]
 [0.3 0.  0.7]
 [0.5 0.  0.5]]


In [5]:
#Random walk on Markov Chain
n=15
start_state = 0
print(state[start_state], "-->",end="")
prev_state = start_state

while n-1:
    curr_state = np.random.choice([0,1,2],p=A[prev_state])
    print(state[curr_state],"-->",end=" ")
    prev_state = curr_state
    n-=1
print("stop")

Burger -->Hotdog --> Hotdog --> Burger --> Burger --> Pizza --> Hotdog --> Hotdog --> Hotdog --> Burger --> Pizza --> Hotdog --> Burger --> Burger --> Pizza --> stop


In [7]:
#Approach 1: Monte Carlo
steps = 10**6
start_state = 0
pi = np.array([0,0,0])
pi[start_state]=1
prev_state = start_state

i=0
while i<steps:
    curr_state = np.random.choice([0,1,2],p=A[prev_state])
    pi[curr_state]+=1
    prev_state = curr_state
    i+=1
print("π =",pi/steps)

π = [0.352216 0.211546 0.436239]


In [8]:
#Approach 2: Repeated Matrix Multiplication
steps = 10**3
A_n = A
i=0
while i<steps:
    A_n =np.matmul(A_n,A)
    i+=1
print("A^n = \n",A_n,"\n")
print("π =",A_n[0])

A^n = 
 [[0.35211268 0.21126761 0.43661972]
 [0.35211268 0.21126761 0.43661972]
 [0.35211268 0.21126761 0.43661972]] 

π = [0.35211268 0.21126761 0.43661972]


In [9]:
#Approach 3 : Finding Left Eigen Vectors
import scipy.linalg
values,left = scipy.linalg.eig(A,right=False,left=True)
print("left eigen vectos = \n",left,"\n")
print("eigen values = \n",values)

left eigen vectos = 
 [[-0.58746336+0.j         -0.16984156-0.35355339j -0.16984156+0.35355339j]
 [-0.35247801+0.j          0.67936622+0.j          0.67936622-0.j        ]
 [-0.72845456+0.j         -0.50952467+0.35355339j -0.50952467-0.35355339j]] 

eigen values = 
 [ 1.  +0.j        -0.15+0.3122499j -0.15-0.3122499j]


In [11]:
pi =left[:,0]
pi_normalized = [(x/np.sum(pi)).real for x in pi]
pi_normalized

[0.3521126760563379, 0.21126760563380298, 0.43661971830985913]

In [14]:
def find_prob(seq,A,pi):
    strat_state = seq[0]
    prob = pi[strat_state]
    prev_state = strat_state
    for i in range(1,len(seq)):
        curr_state=seq[i]
        prob *= A[prev_state][curr_state]
        prev_state = curr_state
    return prob

print(find_prob([1,2,2,0],A,pi_normalized))

0.03697183098591552
